@startuml Forgot/Reset Password
    actor User as user
    participant Frontend as frontend
    participant AuthService as authService
    database AuthDB as authDB
    participant Redis as redis
    participant RabbitMQ as rabbitMQ
    participant EmailService as emailService

    group #LightGreen Forgot password flow
        user -> frontend: Click button "Forgot password"
        frontend -> authService: POST /password/forgot
        authService -> authDB: Check user exists with email
        authDB --> authService: Return user
        authService -> authService: Generate token
        authService -> redis: Store token with TTL
        redis --> authService: Return success

        group #LightYellow Publish send email reset password event
            authService -> rabbitMQ: Publish a reset password message to queue
            emailService -> rabbitMQ: Consume the reset password message\n from queue then send email
        end
        authService -> frontend: Return success
        frontend -> user: Popup message "Check your email for the reset password link"
    end

    group #LightGreen Reset password flow
        user -> frontend: Click link reset password in email
        frontend -> authService: POST /password/reset
        authService -> redis: Validate token
        redis --> authService: Return success
        authService -> authDB: Update new password for user
        authDB --> authService: Return success
        authService -> redis: Delete token
        authService -> frontend: Return success
        frontend -> user: Popup message "Reset password successfully"
    end

@enduml